# Note, this is a basic use of Cloudformation with disregard for Security Group Access
# You should always update Security Group Access with your own IP Address to ensure your instances security.
#
# How to validate template
# aws cloudformation validate-template --template-body file:////path//cloudformation//Nested//ec2-infra.yml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template deploys an AutoScaling Launch Config and Group

Parameters: 

  KeyName:
    Description: "Enter an existing EC2 KeyPair. Default is MyEC2Key"
    Type: "String"
    Default: "MyEC2Key"

# 	Value of property InstanceType must be of type String
  InstanceType: 
    Description: "Enter t2.micro or m1.small. Default is t2.micro."
    Type: "String"
    Default: "t2.micro"
    AllowedValues: 
      - "t2.micro"
      - "m1.small"

  PublicSubnetsParameter:
    Description: "Subnets to launch instances into"
    Type: "List<AWS::EC2::Subnet::Id>"

  ECSHostSecurityGroup:
    Description: "Select the Security Group to use for the EC2 hosts"
    Type: "AWS::EC2::SecurityGroup::Id"

  APPELBUrl:
    Description: "A reference to the Application Load Balancer"
    Type: "String"

  LoadBalancer:
    Description: "A reference to the Webserver Load Balancer"
    Type: "String"

  IamInstanceProfile:
    Description: "A reference to the IamInstanceProfile"
    Type: "String"

  RegionAMI:
    Description: "A reference to the Region AMI"
    Type: "String"

  MinParameter:
    Description: "A reference to the MinSize"
    Type: "String"

  MaxParameter:
    Description: "A reference to the MaxSize"
    Type: "String"

  DesParameter:
    Description: "A reference to the DesiredCapacity"
    Type: "String"


Resources:

  # Auto Scaling Launch Configuration
  LaunchConfiguration:
    Type: "AWS::AutoScaling::LaunchConfiguration"
    Properties:
      AssociatePublicIpAddress: "true"
      KeyName:
        Ref: "KeyName"
      ImageId: !Ref "RegionAMI"
      InstanceType:
        Ref: "InstanceType"
      IamInstanceProfile:
        Ref: "IamInstanceProfile"
      SecurityGroups:
      - Ref: "ECSHostSecurityGroup"
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          yum install nginx htop telnet git awslogs python-pip aws-cfn-bootstrap -y
          yum update -y
          mkdir -p /etc/nginx/sites-enabled
          mkdir -p /etc/nginx/sites-available

          echo "[plugins]
          cwlogs = cwlogs
          [default]
          region = ${AWS::Region}" > /etc/awslogs/awscli.conf
          service awslogs start
          chkconfig awslogs on

          mkdir -p /home/www/public_html/devel.timeclone.com
          echo "<?php phpinfo(); ?>" > /home/www/public_html/devel.timeclone.com/index.php
          chown -R nginx:nginx /home/www/public_html/devel.timeclone.com
          chmod -R +x /home/www/public_html/devel.timeclone.com

          echo "server {
          server_name devel.timeclone.com;
          listen 80;
          
          root /home/www/public_html/devel.timeclone.com/;
          index index.php index.html index.htm;

          location / {
          try_files \$uri \$uri/ /index.php?\$args;
          }

          location ~ \\.php\$ {
          try_files \$uri =404;
          fastcgi_split_path_info ^(.+\.php)(/.+)\$;
          fastcgi_pass php;
          fastcgi_index index.php;
          fastcgi_param SCRIPT_FILENAME \$document_root\$fastcgi_script_name;
          include fastcgi_params;
          fastcgi_read_timeout 300;
          }
          }" > /etc/nginx/sites-available/devel.timeclone.com

          ln -sf /etc/nginx/sites-available/devel.timeclone.com /etc/nginx/sites-enabled/
          
          echo "server {
          listen   80 default;
          server_name  _;
          access_log  /var/log/nginx/localhost.access.log;
          location / {
           root  /usr/share/nginx/html;
          index index.html index.htm index.php;
          }
          }" > /etc/nginx/sites-available/default
         
          ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
         
          echo "proxy_redirect		off;
          client_body_buffer_size	256K;
          client_max_body_size	12m;
          proxy_connect_timeout	600;
          proxy_send_timeout	600;
          proxy_read_timeout	600;
          proxy_buffer_size	128k;
          proxy_buffers		4 256k;
          proxy_busy_buffers_size	256k;" > /etc/nginx/proxy.conf

          echo "user nginx;
          worker_processes auto;
          pid /var/run/nginx.pid;
       
          events {
          worker_connections 1024;
          multi_accept on;
          use epoll;
          }
       
          worker_rlimit_nofile 100000;

          http {

          ##
          # Basic Settings 
          ##
          sendfile on;
          tcp_nopush on;
          tcp_nodelay on;
          keepalive_timeout 65;
          types_hash_max_size 2048;
          server_tokens off;
         
          include /etc/nginx/mime.types;
          default_type application/octet-stream;
         
          # set client body size to 32M #
          client_max_body_size 32M;

          ##
          # Logging Settings
          ##
          access_log /var/log/nginx/access.log;
          error_log /var/log/nginx/error.log;
         
          ##
          # Gzip Settings
          ##
          gzip on;
          gzip_disable "msie6";
          gzip_static on;
          gzip_vary on;
          gzip_proxied any;
          gzip_comp_level 9;
          gzip_buffers 16 8k;
          gzip_http_version 1.1;
          gzip_types text/plain text/css text/csv application/json application/javascript application/x-javascript image/x-icon text/xml application/xml application/xml+rss text/javascript;
       
          ##
          # open_file_cache optimization
          ##
          open_file_cache max=200000 inactive=50s;
          open_file_cache_valid 60s;
          open_file_cache_min_uses 2;
          open_file_cache_errors on;
       
          ##
          # Upstream Server
          ##
          upstream php {
          server ${APPELBUrl}:9000;
          }
       
          ##
          # Virtual Host Configs
          ##
          include /etc/nginx/conf.d/*.conf;
          include /etc/nginx/sites-enabled/*;
          }" > /etc/nginx/nginx.conf

          service nginx start
          chkconfig nginx on
          /opt/aws/bin/cfn-signal -e 0 -r 'server setup complete' "${WaitHandle}"  > /tmp/userdata.log

  WaitHandle:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  WaitCondition:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !Ref "WaitHandle"
      Timeout: '600'

  # Auto Scaling Group Basic Setup
  AutoScalingGroup: 
    Type: "AWS::AutoScaling::AutoScalingGroup"
    Properties: 
      MinSize: !Ref "MinParameter"
      MaxSize: !Ref "MaxParameter"
      DesiredCapacity: !Ref "DesParameter"
      LaunchConfigurationName:
        Ref: "LaunchConfiguration"
      VPCZoneIdentifier:
        Ref: "PublicSubnetsParameter"
      LoadBalancerNames:
      - Ref: "LoadBalancer"
      HealthCheckGracePeriod: "300"
      HealthCheckType: "ELB"
      Tags:
      - Key: "Name"
        Value: "Webserver-AG"
        PropagateAtLaunch: 'true'

  # Auto ScalingUp Policy - Basic Setup
  WebServerScaleUpPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName:
        Ref: "AutoScalingGroup"
      Cooldown: '300'
      ScalingAdjustment: '1'

  # Auto ScalingDown Policy - Basic Setup
  WebServerScaleDownPolicy:
    Type: "AWS::AutoScaling::ScalingPolicy"
    Properties:
      AdjustmentType: "ChangeInCapacity"
      AutoScalingGroupName:
        Ref: "AutoScalingGroup"
      Cooldown: '300'
      ScalingAdjustment: '-1'


Outputs:

  AutoScalingGroupID: 
    Description: "Auto Scaling Group Reference ID"
    Value: !Ref "AutoScalingGroup"

  AutoScalingUpPolicy: 
    Description: "Auto Scaling Up Policy Reference ID"
    Value: !Ref "WebServerScaleUpPolicy"

  AutoScalingDownPolicy: 
    Description: "Auto Scaling Down Policy Reference ID"
    Value: !Ref "WebServerScaleDownPolicy"


