# Note, this is a basic use of Cloudformation with disregard for Security Group Access
# You should always update Security Group Access with your own IP Address to ensure your instances security.
#
# Requirement :
# Create a 2 dev server
# - Autoscaling ( min-2, desired-2, max-3)
# - AutoHealing (Web Server)
# - Elastic Load Balancer
# - Has Full Access to S3 and CloudWatch (logging)
# - Build Service with wait handle (cfg-signal)
#
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template is a master to perform the nessesary task to
    perform the following :
    - Create a 2 dev server
    - Autoscaling ( min-2, desired-2, max-3)
    - AutoHealing (Web Server)
    - Elastic Load Balancer
    - Has Full Access to S3 and CloudWatch
    - CloudWatch AutoScaling Alarm and /var/log logging
    - Build Service with wait handle (cfg-signal)

Resources:

  MyRoleAccess:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-s3sw-role.yml"
      TimeoutInMinutes: '5'

  MyS3Bucket:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-s3.yml"
      TimeoutInMinutes: '5'

  MyVPC:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-vpc.yml"
      TimeoutInMinutes: '5'
      Parameters:
        VpcCIDR: "10.0.0.0/16"
        PublicSubnet1CIDR: "10.0.1.0/24"
        PublicSubnet2CIDR: "10.0.2.0/24"
        PrivateSubnet1CIDR: "10.0.3.0/24"
        PrivateSubnet2CIDR: "10.0.4.0/24"
        FlowLogRole: !GetAtt "MyRoleAccess.Outputs.VPCFlowLogRoleArn"

  SecurityGroup:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-sg.yml"
      TimeoutInMinutes: '5'
      Parameters:
        EnvironmentName: !Ref "AWS::StackName"
        VPCParameter: !GetAtt "MyVPC.Outputs.VPC"
        PublicSubnet1Parameter: !GetAtt "MyVPC.Outputs.PublicSubnet1"
        PublicSubnet2Parameter: !GetAtt "MyVPC.Outputs.PublicSubnet2"

  MyELB:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-elb.yml"
      TimeoutInMinutes: '5'
      Parameters:
        ELBSecurityGroup: !GetAtt "SecurityGroup.Outputs.ELBSecurityGroup"
        PublicSubnetsParameter: !GetAtt "MyVPC.Outputs.PublicSubnets"
        S3BackupBucket: !GetAtt "MyS3Bucket.Outputs.S3Backup"

  MyRDS:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-rds.yml"
      TimeoutInMinutes: '5'
      Parameters:
#        EnvironmentName: !Ref "AWS::StackName"
        VPCParameter: !GetAtt "MyVPC.Outputs.VPC"
        RDSSecurityGroup: !GetAtt "SecurityGroup.Outputs.RDSSecurityGroup"
        PrivateSubnetsParameter: !GetAtt "MyVPC.Outputs.PrivateSubnets"

  MyAutoScaling:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-autoscaling.yml"
      TimeoutInMinutes: '5'
      Parameters:
        ECSHostSecurityGroup: !GetAtt "SecurityGroup.Outputs.ECSHostSecurityGroup"
        LoadBalancer: !GetAtt "MyELB.Outputs.LoadBalancer"
        IamInstanceProfile: !GetAtt "MyRoleAccess.Outputs.S3CWAccessInstanceProfile"
        PublicSubnetsParameter: !GetAtt "MyVPC.Outputs.PublicSubnets"


  MyCloudWatch:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/nested-cloudwatch.yml"
      TimeoutInMinutes: '5'
      Parameters:
        AutoScalingGroup: !GetAtt "MyAutoScaling.Outputs.AutoScalingGroupID"
        WebServerScaleUpPolicy: !GetAtt "MyAutoScaling.Outputs.AutoScalingUpPolicy"
        WebServerScaleDownPolicy: !GetAtt "MyAutoScaling.Outputs.AutoScalingDownPolicy"


Outputs:
  Webserver:
    Description: "Public IP address of the new EC2 instance"
    Value:
      Fn::Join:
        - ''
        - - "http://"
          - !GetAtt "MyELB.Outputs.LoadBalancerUrl"
          - "/"
