# Note, this is a basic use of Cloudformation with disregard for Security Group Access
# You should always update Security Group Access with your own IP Address to ensure your instances security.
#
# How to validate template
# aws cloudformation validate-template --template-body file:////path//cloudformation//Nested//master.yml
---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
    This template is a master to perform Cloudformation Nested 

Resources:
  SecurityGroup:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/security-group.yml"
      TimeoutInMinutes: '5'
      Parameters:
        EnvironmentName: !Ref "AWS::StackName"

#  MyInstance:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: "https://s3-ap-southeast-1.amazonaws.com/cf-templates-19sg5y0d6d084-ap-southeast-1/ec2-infra.yml"
#      TimeoutInMinutes: '5'
#      Parameters: 
#        SecurityGroup: !GetAtt "SecurityGroup.Outputs.ECSHostSecurityGroup"
#
#
#Outputs:
#  Webserver:
#    Description: "Public IP address of the new EC2 instance"
#    Value:
#      Fn::Join:
#        - ''
#        - - "http://"
#          - !GetAtt "MyInstance.Outputs.IP"
#          - "/"
